// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.1
// source: gorpc.proto

package jrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GoPBRpcRequestData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq           uint64 `protobuf:"varint,1,opt,name=Seq,proto3" json:"Seq,omitempty"`
	RpcMethodId   uint32 `protobuf:"varint,2,opt,name=RpcMethodId,proto3" json:"RpcMethodId,omitempty"`
	ServiceMethod string `protobuf:"bytes,3,opt,name=ServiceMethod,proto3" json:"ServiceMethod,omitempty"`
	NoReply       bool   `protobuf:"varint,4,opt,name=NoReply,proto3" json:"NoReply,omitempty"`
	InParam       []byte `protobuf:"bytes,5,opt,name=InParam,proto3" json:"InParam,omitempty"`
}

func (x *GoPBRpcRequestData) Reset() {
	*x = GoPBRpcRequestData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gorpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoPBRpcRequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoPBRpcRequestData) ProtoMessage() {}

func (x *GoPBRpcRequestData) ProtoReflect() protoreflect.Message {
	mi := &file_gorpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoPBRpcRequestData.ProtoReflect.Descriptor instead.
func (*GoPBRpcRequestData) Descriptor() ([]byte, []int) {
	return file_gorpc_proto_rawDescGZIP(), []int{0}
}

func (x *GoPBRpcRequestData) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GoPBRpcRequestData) GetRpcMethodId() uint32 {
	if x != nil {
		return x.RpcMethodId
	}
	return 0
}

func (x *GoPBRpcRequestData) GetServiceMethod() string {
	if x != nil {
		return x.ServiceMethod
	}
	return ""
}

func (x *GoPBRpcRequestData) GetNoReply() bool {
	if x != nil {
		return x.NoReply
	}
	return false
}

func (x *GoPBRpcRequestData) GetInParam() []byte {
	if x != nil {
		return x.InParam
	}
	return nil
}

type GoPBRpcResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq   uint64 `protobuf:"varint,1,opt,name=Seq,proto3" json:"Seq,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	Reply []byte `protobuf:"bytes,3,opt,name=Reply,proto3" json:"Reply,omitempty"`
}

func (x *GoPBRpcResponseData) Reset() {
	*x = GoPBRpcResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gorpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoPBRpcResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoPBRpcResponseData) ProtoMessage() {}

func (x *GoPBRpcResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_gorpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoPBRpcResponseData.ProtoReflect.Descriptor instead.
func (*GoPBRpcResponseData) Descriptor() ([]byte, []int) {
	return file_gorpc_proto_rawDescGZIP(), []int{1}
}

func (x *GoPBRpcResponseData) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GoPBRpcResponseData) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GoPBRpcResponseData) GetReply() []byte {
	if x != nil {
		return x.Reply
	}
	return nil
}

var File_gorpc_proto protoreflect.FileDescriptor

var file_gorpc_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x67, 0x6f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6a,
	0x72, 0x70, 0x63, 0x22, 0xa2, 0x01, 0x0a, 0x12, 0x47, 0x6f, 0x50, 0x42, 0x52, 0x70, 0x63, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x65,
	0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x53, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b,
	0x52, 0x70, 0x63, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0b, 0x52, 0x70, 0x63, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x49, 0x64, 0x12, 0x24,
	0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x4e, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x4e, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18,
	0x0a, 0x07, 0x49, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x49, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x22, 0x53, 0x0a, 0x13, 0x47, 0x6f, 0x50, 0x42,
	0x52, 0x70, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x10, 0x0a, 0x03, 0x53, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x53, 0x65,
	0x71, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x08, 0x5a,
	0x06, 0x2e, 0x2f, 0x6a, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gorpc_proto_rawDescOnce sync.Once
	file_gorpc_proto_rawDescData = file_gorpc_proto_rawDesc
)

func file_gorpc_proto_rawDescGZIP() []byte {
	file_gorpc_proto_rawDescOnce.Do(func() {
		file_gorpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_gorpc_proto_rawDescData)
	})
	return file_gorpc_proto_rawDescData
}

var file_gorpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gorpc_proto_goTypes = []interface{}{
	(*GoPBRpcRequestData)(nil),  // 0: jrpc.GoPBRpcRequestData
	(*GoPBRpcResponseData)(nil), // 1: jrpc.GoPBRpcResponseData
}
var file_gorpc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gorpc_proto_init() }
func file_gorpc_proto_init() {
	if File_gorpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gorpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoPBRpcRequestData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gorpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoPBRpcResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gorpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gorpc_proto_goTypes,
		DependencyIndexes: file_gorpc_proto_depIdxs,
		MessageInfos:      file_gorpc_proto_msgTypes,
	}.Build()
	File_gorpc_proto = out.File
	file_gorpc_proto_rawDesc = nil
	file_gorpc_proto_goTypes = nil
	file_gorpc_proto_depIdxs = nil
}
